# Change these first
owner: Feuerwehr-Bad-Erlach # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Homepage
    url: https://www.feuerwehr-bad-erlach.at
    icon: https://www.feuerwehr-bad-erlach.at/wp-content/uploads/2020/07/cropped-Logo-Homepage-2.png
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.feuerwehr-bad-erlach.at
  #baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status
  theme: night
  introTitle: "Service Status Summary"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
